import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Scrape the tag from package JSON
const version = process.env.npm_package_version;

// Scrape the latest content from from the CHANGELOG
// The regular expression matches a leading anchor tag that semantic-release prepends
// to all generated releases. This means that by grabbing the element at index one of the
// array generated by split, we should be grabbing the most recent changelog content

// This solution will potentially break if the semantic-release template changes
// View and troubleshoot the RexExp at https://regexr.com/3kof2

const changelogPath = resolve(__dirname, "..", "CHANGELOG.md");
const changelogContent = readFileSync(changelogPath, { encoding: "utf8" });
const semverAnchorRegEx =
  /<a name="[0-9.]+"><\/a>\n+## \[[0-9.]+\]\([\w://.-]+\) \(\d\d\d\d-\d\d-\d\d\)\n\n/g;
const bodyOfLatestGeneratedChangeLogEntry =
  changelogContent.split(semverAnchorRegEx)[1];

const payload = {
  tag_name: `v${version}`,
  target_commitish: "master",
  name: `v${version}`,
  body: bodyOfLatestGeneratedChangeLogEntry,
  draft: true,
  prerelease: false
};

try {
  const response = await fetch(
    `https://api.github.com/repos/DecipherNow/gm-fabric-dashboard/releases`,
    {
      method: "POST",
      headers: {
        Authorization: `token ${process.env.GITHUB_ACCESS_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    }
  );

  if (!response.ok) {
    // The server responded with a status code outside the 2xx range.
    console.log(await response.text());
    console.log(response.status);
    console.log(Object.fromEntries(response.headers));
    process.exit(1);
  }

  console.log(await response.json());
} catch (error) {
  // A network-level failure: the request was made but no response was received.
  console.log("Error", error.message);
  process.exit(1);
}
