name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and draft GitHub release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build
        env:
          CI: true
          TZ: America/New_York

      - name: Draft GitHub release
        run: npm run draft-github-release
        env:
          GITHUB_ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
